### ISSUE TITLE
zbus is a heavy dependency

### ISSUE THREAD

**Issue by parasyte** [frewsxcv/rust-dark-light#15]
`zbus` replaced `dbus` in edff243a182d3293b8d81d3d9417ed9f725bc3cb and the change was requested in https://github.com/frewsxcv/rust-dark-light/pull/4#discussion_r779083783

Some stats according to `lib.rs`:

- https://lib.rs/crates/dbus: 405KB + ~0.3–260KB (dependencies; 2 are required)
- https://lib.rs/crates/zbus: 1MB + ~5–7MB (dependencies; 27 are required)

Related: https://gitlab.freedesktop.org/dbus/zbus/-/issues/254

**Comment by frewsxcv** [comment]
If you would like to open a PR replacing it, then I'd review it

**Comment by Be-ing** [comment]
Please do not replace zbus with dbus! dbus requires a C library. zbus is pure Rust.

**Comment by frewsxcv** [comment]
Maybe we could have it behind a feature flag? So you can choose one or the other

**Comment by Be-ing** [comment]
If you insist, but IMO it'd be pretty silly to have two implementations of the same thing.

**Comment by frewsxcv** [comment]
Nah I don't insist, I'd rather have a pure-Rust dependency tree

**Comment by frewsxcv** [comment]
> [(dependencies; 27 are required)](https://lib.rs/crates/zbus: 1MB + ~5–7MB (dependencies; 27 are required))

For reference: https://gitlab.freedesktop.org/dbus/zbus/-/blob/main/zbus/Cargo.toml

**Comment by mwcampbell** [comment]
I want to push back a bit on this one, because I anticipate the same complaint about [AccessKit](https://github.com/AccessKit/accesskit)'s upcoming zbus-based AT-SPI implementation, and because I think choosing light versus dark mode is an accessibility issue in itself. While we should certainly avoid adding gratuitous complexity and code bloat, we should also keep in mind that a human interface that accommodates the needs of a variety of users is fundamentally not a simple, small problem, so it can't have a simple, small solution. Whether or not D-Bus is over-complicated, it's what we have on the free desktops, and meeting the needs of users must come first. I think dark-light is right to prefer a pure-Rust dependency tree. So @frewsxcv, you should feel free to dismiss this issue.

**Comment by Be-ing** [comment]
I'll leave this open for now

**Comment by jacksongoode** [comment]
Is zbus any lighter today than when this issue was made? @frewsxcv

**Comment by jacksongoode** [comment]
I think zbus is actually smaller now?

**Comment by parasyte** [comment]
https://lib.rs/crates/zbus gives a rough estimate of weight. When I created this, its dependencies were estimates at 5~7MB. It's now 10~26MB.

**Comment by jacksongoode** [comment]
Hmm, there's not really any alternative in the rust world though is there? I suppose dark-light could make z/dbus a feature that can be installed separately

**Comment by Be-ing** [comment]
No, there isn't a Rust alternative to zbus. There's no actionable request here. If you don't like zbus, improve it or write an alternative.

**Comment by parasyte** [comment]
It is actionable, which is different from maintainers having no interest.

**Comment by frewsxcv** [comment]
There is no actionable request.
