### ISSUE TITLE
Add new function that takes a callback which gets run whenever dark/light mode changes

### ISSUE THREAD

**Issue by frewsxcv** [frewsxcv/rust-dark-light#3]
- [ ] Mac
- [ ] Windows
- [ ] Linux

**Comment by edfloreshz** [comment]
I'm on it!

**Comment by frewsxcv** [comment]
Some relevant macOS links:

- https://stackoverflow.com/a/56091382/15385214
- https://stackoverflow.com/a/26472651/15385214
    - [Maybe relevant Rust code](https://github.com/dataluscorp/browser/blob/4c4497829761e1960f453d47316ddf627195e748/toolkit/components/glean/src/init/user_activity.rs#L48-L52)

**Comment by frewsxcv** [comment]
https://github.com/cormacrelf/dark-notify

**Comment by edfloreshz** [comment]
I have a working function that takes a callback.

I'm calling `dark-light::detect` on a loop and invoking the callback function when the theme changes. 

I want to leave this behavior for distros that haven't yet implemented `color-scheme` since there's no single way we can get every DE to notify us of a change in theme. Let me know if there's a better way to do this. 

For the ones that have, I would like to get a notification from `dbus` when that key changes value, can `dbus` do that?

**Comment by Be-ing** [comment]
Yes you can get a notification from dbus. That would be better than a busy wait loop.

**Comment by edfloreshz** [comment]
Any ideas for distros that haven't implemented `color-scheme`? I really don't like that loop 😅

**Comment by Be-ing** [comment]
For the ones that rely on config files, you could use https://lib.rs/crates/notify

**Comment by edfloreshz** [comment]
I considered using that crate, I'll see what I can do. 😉

**Comment by edfloreshz** [comment]
> Yes you can get a notification from dbus. That would be better than a perpetual loop.

I have little experience working with dbus, could you point me in the right direction?

**Comment by Be-ing** [comment]
I don't have much experience with dbus either, but I do know it can emit signals that your application can receive. [This](https://flatpak.github.io/xdg-desktop-portal/#gdbus-signal-org-freedesktop-portal-Settings.SettingChanged) looks like the signal we want.

**Comment by edfloreshz** [comment]
Big help! Thanks 🙏🏼

**Comment by d2weber** [comment]
See this repo where I implemented listening color scheme preferences from freedesktops dbus: 
https://github.com/d2weber/color-scheme-hook
